// Do not edit. This file is machine generated by the Resource DLL Wizard.

library BookCatalogTests;

{ITE} {RCFileType} {Win32\Debug\BookCatalogTests_DRC.rc}

{$R 'Win32\Debug\BookCatalogTests_DRC.res' 'Win32\Debug\BookCatalogTests_DRC.rc'}

{$E ENG}

begin
end.
